
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package a_sintactico_robot;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 8;
  public static final int EOF = 0;
  public static final int ROBOT = 2;
  public static final int ACCION = 4;
  public static final int NUMERO = 6;
  public static final int IGUAL = 7;
  public static final int ERROR = 1;
  public static final int METODO = 3;
  public static final int IDENTIFICADOR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "ERROR",
  "ROBOT",
  "METODO",
  "ACCION",
  "IDENTIFICADOR",
  "NUMERO",
  "IGUAL",
  "PUNTO"
  };
}

